import { openSettings } from './helpers';
import { expect, test } from '@playwright/test';
import type { Page } from '@playwright/test';

async function enter(page: Page, name = 'Sean') {
  await page.goto('/');
  const skip = page.getByRole('button', { name: 'Skip intro' });
  if (await skip.isVisible()) await skip.click();
  await page.getByRole('button', { name: 'Begin the journey', exact: true }).click();
  await page.getByLabel('Your name', { exact: true }).fill(name);
  await page.getByRole('button', { name: 'Yes', exact: true }).click();
}

async function prepare(page: Page) {
  await page.getByRole('button', { name: 'Start Stage 1', exact: true }).click();
}

test('complete onboarding and Stage 1; save, notes and future-stage boundary', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Forge of Ideas' })).toBeVisible();
  await page.screenshot({ path: `artifacts/${testInfo.project.name}-landing.png`, animations: 'disabled' });
  await page.getByRole('button', { name: 'Begin the journey', exact: true }).click();
  await page.getByRole('button', { name: 'Yes', exact: true }).click();
  await expect(page.getByRole('alert')).toHaveText('Please enter at least 2 characters.');
  await page.getByLabel('Your name', { exact: true }).fill('  Sean  ');
  await page.screenshot({ path: `artifacts/${testInfo.project.name}-name.png`, animations: 'disabled' });
  await page.getByRole('button', { name: 'Yes', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome, Sean.' })).toBeVisible();
  await page.screenshot({ path: `artifacts/${testInfo.project.name}-prologue.png`, animations: 'disabled' });
  await prepare(page);
  await expect(page.getByRole('button', { name: 'View your journey' })).toBeDisabled();
  await page.getByRole('button', { name: 'How', exact: true }).click();
  await expect(page.locator('.dialogue-copy')).toContainText('choices Bradbury makes');
  await expect(page.getByRole('button', { name: 'View your journey' })).toBeDisabled();
  await page.getByRole('button', { name: 'this moment', exact: true }).click();
  await page.getByRole('button', { name: 'so tense', exact: true }).click();
  await expect(page.getByRole('button', { name: 'View your journey' })).toBeEnabled();
  await page.screenshot({ path: `artifacts/${testInfo.project.name}-stage1.png`, animations: 'disabled' });
  await page.getByRole('button', { name: 'Quest journal', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByText('3 / 3 discovered')).toBeVisible();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download notes' }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe('forge-of-ideas-quest-notes.txt');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'View your journey' }).click();
  await expect(page.getByRole('heading', { name: 'Your journey' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Open Generate', exact: true })).toBeVisible();
  await page.screenshot({ path: `artifacts/${testInfo.project.name}-map.png`, animations: 'disabled' });
  await page.reload();
  await page.getByRole('button', { name: 'Continue your journey' }).click();
  await expect(page.getByRole('button', { name: 'Continue to Generate', exact: true })).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('forge-of-ideas:progress:v1')!).completed)).toBe(true);
  expect(errors).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});

test('settings, focus, home and cancellation preserve progress', async ({ page }) => {
  await enter(page, 'Maya');
  await openSettings(page);
  await page.getByLabel('Reduce motion', { exact: false }).check();
  await page.getByLabel('Larger dialogue', { exact: false }).check();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByRole('button', { name: 'Ask the raven', exact: true })).toBeFocused();
  await expect(page.locator('.atmosphere canvas')).toHaveCount(0);
  await page.getByRole('button', { name: 'Home', exact: true }).click();
  await page.getByRole('button', { name: 'Begin anew', exact: true }).click();
  await page.getByRole('button', { name: 'Keep my journey' }).click();
  await page.getByRole('button', { name: 'Continue your journey' }).click();
  await expect(page.getByRole('heading', { name: 'Welcome, Maya.' })).toBeVisible();
  await prepare(page);
  for (const label of ['How', 'this moment', 'so tense']) await page.getByRole('button', { name: label, exact: true }).click();
  const scroll = page.locator('.dialogue-scroll');
  const copy = page.locator('.dialogue-copy');
  const scrollBox = await scroll.boundingBox();
  const copyBox = await copy.boundingBox();
  expect(scrollBox && copyBox && copyBox.y + copyBox.height <= scrollBox.y + scrollBox.height).toBeTruthy();
});

test('all six stages and the ending remain playable when browser storage is blocked', async ({ page }) => {
  await page.addInitScript(() => {
    Storage.prototype.getItem = () => { throw new Error('Storage is blocked'); };
    Storage.prototype.setItem = () => { throw new Error('Storage is blocked'); };
  });
  await enter(page, 'Alex');
  await expect(page.getByRole('heading', { name: 'Welcome, Alex.' })).toBeVisible();
  await expect(page.getByText('Progress could not be saved')).toBeVisible();
  await prepare(page);
  await page.getByRole('button', { name: 'How', exact: true }).click();
  await expect(page.getByRole('button', { name: 'How', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'this moment', exact: true }).click();
  await page.getByRole('button', { name: 'so tense', exact: true }).click();
  await page.getByRole('button', { name: 'View your journey' }).click();
  await page.getByRole('button', { name: 'Continue to Generate', exact: true }).click();
  await page.getByRole('button', { name: 'Enter the Forge', exact: true }).click();
  await page.getByRole('button', { name: 'Start gathering', exact: true }).click();
  await page.getByRole('button', { name: 'Collect idea', exact: true }).click();
  await page.getByRole('button', { name: 'Explore Sensory detail', exact: true }).click();
  await page.getByRole('button', { name: 'Collect idea', exact: true }).click();
  await page.getByRole('button', { name: 'Review my pouch', exact: true }).click();
  await page.getByRole('button', { name: 'Complete Stage 2', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Review Generate', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Continue to Sort', exact: true }).click();
  await page.getByRole('button', { name: 'Start sorting', exact: true }).click();
  await page.getByRole('button', { name: 'Select Lifelike AI', exact: true }).click();
  await page.getByRole('button', { name: 'Move selected idea to Central', exact: true }).click();
  await page.getByRole('button', { name: 'Select Sensory detail', exact: true }).click();
  await page.getByRole('button', { name: 'Move selected idea to Supporting', exact: true }).click();
    await page.getByRole('button', { name: 'Complete Stage 3', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Review Sort', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Continue to Connect', exact: true }).click();
  await page.getByRole('button', { name: 'Enter the chamber', exact: true }).click();
  await page.getByRole('button', { name: 'Select central idea: Lifelike AI', exact: true }).click();
  await page.getByRole('button', { name: 'Select supporting idea: Sensory detail', exact: true }).click();
  await page.getByRole('button', { name: 'Forge connection', exact: true }).click();
  await page.getByRole('button', { name: 'Write connecting statement', exact: true }).click();
  await page.getByRole('textbox', { name: /How does the supporting idea/ }).fill('Lifelike details make an artificial experience feel threatening.');
  await page.getByRole('button', { name: 'Save statement', exact: true }).click();
  await page.getByRole('button', { name: 'Complete Stage 4', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Review Connect', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Continue to Elaborate', exact: true }).click();
  await page.getByRole('button', { name: 'Enter the chamber', exact: true }).click();
  await page.getByRole('button', { name: 'Select crystal: Lifelike AI', exact: true }).click();
  await page.getByRole('button', { name: 'Add Evidence rune', exact: true }).click();
  await page.getByRole('button', { name: 'Add Effect rune', exact: true }).click();
  await page.getByRole('button', { name: 'Write elaborated response', exact: true }).click();
  await page.getByRole('textbox', { name: /Write how your evidence/ }).fill('The sensory detail develops my idea about a lifelike artificial experience. I would check this interpretation against the classroom extract.');
  await page.getByRole('dialog').getByRole('button', { name: 'Review infusions', exact: true }).click();
  await page.getByRole('button', { name: 'Complete Stage 5', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Review Elaborate', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Continue to Challenge', exact: true }).click();
  await page.getByRole('button', { name: 'Face the Beast', exact: true }).click();
  await page.getByRole('button', { name: 'Take aim', exact: true }).click();
  await page.getByRole('button', { name: 'Select infusion: Lifelike AI', exact: true }).click();
  await page.getByRole('slider', { name: /Horizontal aim/ }).fill('50');
  await page.getByRole('button', { name: 'Launch infusion', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'The Beast retreats.', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Complete Stage 6', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'A journey well forged.', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Enter the Archival Hall through the portal', exact: true }).click();
  await page.getByRole('button', { name: 'Open your journey record', exact: true }).click();
  await page.getByRole('textbox', { name: /One thought to carry forward/ }).fill('I can explain my ideas more clearly.');
  await expect(page.getByRole('dialog')).toContainText('Could not save in this browser.');
  await expect(page.getByRole('dialog')).toContainText('Your developed ideas');
  await page.getByRole('button', { name: 'Back to the Hall', exact: true }).click();
  await expect(page.getByText('Progress could not be saved')).toBeVisible();
});
